name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test
  ELIXIR_VERSION: 1.10.4
  OTP_VERSION: 23.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_coverage:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        name: Setup Elixir
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - uses: actions/cache@v3
        with:
          path: |
            src/deps
            src/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

      - name: Run Tests
        run: mix coveralls.github
